### ISSUE TITLE
Feature Request: Support rotation

### ISSUE THREAD

**Issue by zerobearing2** [mapgears/ol3-google-maps#100]
Hi-

I've read the rotate [limitation](https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#rotation), and see that its not currently supported. I'm relatively new to Openlayers 3, and don't fully grasp the limitations with Google maps. We have an immediate need for OpenLayers, Google maps, and map rotation. Therefore, we are willing to sponsor (pay for) the solution, if someone here can add the rotate functionality?

**Comment by dmorissette** [comment]
Hi, unfortunately @adube who is the ol3-gm lead developer is on vacation for the next 2 weeks, but if you want to contact us at info@mapgears.com we can discuss options for funding the feature and make sure we have responses on the feasibility and cost as soon as @adube is back from vacation.

**Comment by samuellapointe** [comment]
Hello @zerobearing2,

We implemented a workaround for the rotation issue yesterday (#109). It's not entirely perfect since we're circumventing the limitations of the Google Maps API, but it allows the map to be rotated freely with the same controls as OpenLayers 3. 

I'll close the issue since it's solved, but feel free to re-open it if there's still any issues with the rotation.
