### ISSUE TITLE
ol.Animation.Pan not working with Google Layer

### ISSUE THREAD

**Issue by vandertyson** [mapgears/ol3-google-maps#128]
When i use **ol.Animation.Pan** with Google layer, the animation is not shown. When i call the panToPoint() function it just simply sets center of the view without any smooth flying effect. Please help. I'm using **Angular 2 and Typescript.** Here is my map initialization() and panToPoint() functions in the component.

```
 private map:any;
 private view:any;

 initialization(){
    let controller = this;
    this.view = new ol.View({
            center: ol.proj.transform([0, 0], 'EPSG:4326', 'EPSG:3857'),
            zoom: 2,
            minZoom: 1,
            maxZoom: 21
        });

    var googleLayer = new olgm.layer.Google();
        this.map = new ol.Map({
            layers: [googleLayer],
            controls: ol.control.defaults({ attribution: false, rotate: false }).extend([attribution]),
            target: 'map',
            view: controller.view
        });

    var olGM = new olgm.OLGoogleMaps({ map: this.map }); 
    olGM.activate();
}

panToPoint(lat, lon){
     let controller = this;
     var destination = ol.proj.transform([+lon, +lat], 'EPSG:4326', 'EPSG:3857');
     var pan = ol.animation.pan({
          duration: 2000,
          source: (controller.view.getCenter())
        });
     this.map.beforeRender(pan);
     this.view.setCenter(destination);
}
```

**Comment by adube** [comment]
Hi @vandertyson.  Thanks for your interest in OL3-Google-Maps.

This is currently a limitation of the library.  See: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md#kinetic-pan

The source of the problem is while the ol3 map is animating a pan, its center is not the one you see "while" the animation is in progress.  It's the one at the end of the animation.  There's currently no way to detect the actual "center that you see while animating" in ol3, so what you want to do is currently not possible.  OL3-Google-Maps listens to the center change.  That's why it jumps to the end of the animation.

It's a known limitation due to the design of OpenLayers.  It's discussed in here: https://github.com/openlayers/ol3/issues/298.  You can contribute to the discussion from there or even better contribute its development if you want.

HTH

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
