### ISSUE TITLE
CSS height on 'map' class

### ISSUE THREAD

**Issue by saurabhumalkar** [mapgears/ol3-google-maps#132]
It seems that if map class height css is specified in %, it does not work. For example in layout.css if I remove height attribute on map class or change it to 100%, the example stops working.

**Comment by geopamplona** [comment]
Good morning, your problem is the same to me. I always need to add height to the map div for the google layers to work fine.
The downside of this is that the map is not responsive.
Maybe it can be solved by css?

**Comment by adube** [comment]
The problem seems to be caused by the fact that the div in which the Google Maps' map is rendered inherits its parent height.  If that's what you mean, then I faced this issue once.  The following CSS worked for me (`#map` being the target div where the OL3 map is renderered):

```
#map > div {
  height: 100% !important;
}
```

Please, let us know if that works for you.

**Comment by geopamplona** [comment]
It makes a lot of sense what you propose, but in my case it does not work.
When I give height to the "map" layer if it shows the google layers well; when specific height 100% google layer disappears. I still try css code, maybe it's something that conflicts (although I should not)

**Comment by geopamplona** [comment]
at the moment it works for me

```
#map> div {
height: 100vh! important;
}
```

other forums say that this way is not compatible with older browsers. 
Maybe this is the solution?

I think this solution is not entirely good, because the map is very large.
This is a serious problem to make the map responsive when using google layers.
I have seen that many people have the same problem.
using the examples of mapgears also does not work the proposed solution by @adube

**Comment by adube** [comment]
I think it would be nice to have a "fullscreen" example, in which we try to reproduce the issue and try to fix it at the same time.  That way, the solution that would be found would be a good "tip" for users that are trying to do the same thing.

If anyone's willing to work on the addition of such an example, I could do the review.

**Comment by geopamplona** [comment]
I have raised this case example in jsfiddle:
https://jsfiddle.net/04uLfs61/2/

in the box css I comment the different alternatives raised in this thread

**Comment by adube** [comment]
I'm running this on Chrome and it seems to work fine for me.  Or maybe I'm not understanding the real issue here.  Would you please explain it again?  In what browser can I reproduce the issue?

Thanks

**Comment by geopamplona** [comment]
in the box css I comment the different alternatives raised in this thread

**Comment by geopamplona** [comment]
in the box css I comment the different alternatives raised in this thread

the real problem is that if we apply the height: 100% to all the child layers of the map layer, google layers will still not see correctly

thanks

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
