### ISSUE TITLE
Remove Visibility of Business Poi

### ISSUE THREAD

**Issue by JoeC38** [mapgears/ol3-google-maps#139]
Hi, in the first place, thanks for the library, it is great. The problem I have is that I can´t remove visibility of business poi accesing to the embedded map of google. What I do is:
`var removePoiStyle = [ {
	featureType : "poi.business",
	elementType : "labels",
	stylers : [ {
		visibility : "off"
	} ]
} ];
`
`olGM.getGoogleMapsMap().setOptions({styles : removePoiStyle});`
I have read that there are limitations about style functions and style arrays, but does this affect to change the style of the google map as well? 

Thanks a lot.

**Comment by adube** [comment]
Hi @JoeC38.  Thanks for your interest in ol3-google-maps!

The styling limitations only affect the `ol.layer.Vector` layers, so the issue doesn't come from there.

I think you should be able to accomplish what you want to do by doing it like in this example:
- http://mapgears.github.io/ol3-google-maps/examples/dist/examples/themed.html
- see the js file: http://mapgears.github.io/ol3-google-maps/examples/dist/examples/themed.js

Here's the snippet you could be interested in:

```
var themedLayer = new olgm.layer.Google({
  styles: [{
    "stylers": [{
      "saturation": -100
    },{
       "gamma": 2.25
    }]
  }]
});
```

In the case of calling the `setOptions` method directly, I think it doesn't work because ol3-google-maps needs OpenLayers layer objects to be able to manage the visibility and depending on the chosen type of map ol3-google-maps will create the gmaps layer and add it directly.  I think the options work only with the 'default' layers of gmaps.  I'm not sure about this.

Try the suggested approach and tell us if that worked for you.

**Comment by JoeC38** [comment]
Thanks!!! It works!, That was what I was looking for. Here is my code after been adapted to your guidelines:

```
var googleLayerHyb = new olgm.layer.Google({
  mapTypeId : google.maps.MapTypeId.HYBRID,
  styles:[{
    featureType : "poi",
    elementType : "labels",
    stylers : [{
            visibility : "off"
        }]
    }]
});
```

This way I remove all poi (business,hospitals, schools..) that are not useful for the user.
Thanks a lot.

**Comment by adube** [comment]
Excellent!  Thanks for sharing this.  I'll close this issue now.
