### ISSUE TITLE
syncronizing zoom and pan

### ISSUE THREAD

**Issue by prieston** [mapgears/ol3-google-maps#143]
I noticed that when zooming in and out or pan the map at [this example](http://mapgears.github.io/ol3-google-maps/examples/dist/examples/watchoptions.html) the functionallity is not syncronized at both layers (google maps and vector layer). Can this be syncronized somehow?

**Comment by adube** [comment]
Hi @Prieston 

This example explains how you can toggle on/off the management of layers in OLGM using the watch options.  Let me clarify.

OLGM puts the OpenLayers map on top of Google Maps.  When all 'watch' options are turned off (that's when everything is red in the example), then the layers are rendered by OpenLayers.  Zooming in/out have a 'not synchronized' behavior because the zooming animation is not the same, i.e. Google Maps has its own animation while OpenLayers also has it own.

When you toggle a watcher 'on', you ask OLGM to render the layer directly in Google Maps instead of OpenLayers  (that's when an element is green in the example).  You'll see that from there on the zooming in and out is synchronized with the layers because they are rendered in Google Maps, therefore they follow the Google Maps animation.

That's pretty much it.  I'm closing this issue, now.
