### ISSUE TITLE
Overview map

### ISSUE THREAD

**Issue by rezvanshiravi** [mapgears/ol3-google-maps#162]
After hard working on Google overview map , I found that when I set collapsed option to false in overviewmap control instance, my overviewmap work well but when I set it to true only the first load of overviewmap had shown and by refresh web page it never show again.

I think this is a bug.
So I demands on your team to resolve this issue.

Thanks

**Comment by adube** [comment]
Hello.  Thanks for your interest in OL3-Google-Maps.

We, at Mapgears, are definitely committed to continuing to support this project as long as it will make sense to do so. We use it for our own products and for projects with our customers, and will continue to make it evolve and address issues as we go as part of that work.

However, just like with any open source project, its development is driven by the funding we can get through customer projects, so if there are some limitations that are important to you and your organization, we'd be happy to provide you a quote for a support package or for working on those specific limitations, and of course you are also welcome to work on them yourself and contribute the fix. Note that contributions have to meet some minimum quality requirements in order to be included in the official package, but that's the same as with any mature open source project.

If you would also please create a live example that demonstrate the issue it would be appreciated.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
