### ISSUE TITLE
How to use the npm package?

### ISSUE THREAD

**Issue by fqborges** [mapgears/ol3-google-maps#177]
I have no clue, since:

`var olgm = require('ol3-google-maps');`

and 

`import olgm from 'ol3-google-maps';`

both return an empty object.

EDIT: I am using webpack.

**Comment by adube** [comment]
See: #175

**Comment by flaviocarmo** [comment]
Hi. So, after #175 , what is the way to use the npm package? im making a React.JS app and the ol3gm doesnt work.

**Comment by fqborges** [comment]
Still not working. I dropped the library and synced the ol view with google maps myself: https://gist.github.com/fqborges/92077c4dbde7b646447990a524f3c41a

**Comment by adube** [comment]
>Still not working. I dropped the library and synced the ol view with google maps myself: https://gist.github.com/fqborges/92077c4dbde7b646447990a524f3c41a

The way @fqborges does it is fine as long that you don't mind not having OL and GM animations not perfectly the same.

>Hi. So, after #175 , what is the way to use the npm package? im making a React.JS app and the ol3gm doesnt work.

See: https://github.com/mapgears/ol3-google-maps/pull/175#issuecomment-354770427

It was closed due to being obsolete and we should do as OL does: migrate the code to ES modules.  There's not immediate plan to work on this, other than contributions from users.

Does that clarify?

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
