### ISSUE TITLE
Is using ol3-google-maps legal for commercial use?

### ISSUE THREAD

**Issue by LSG8** [mapgears/ol3-google-maps#179]
I tried to integrate google map in openlayers 3 using ol3-google-maps by mapgear. But I wonder whether is it legal to use it for commercial use?

**Comment by adube** [comment]
ol3-google-maps is legal.  See: https://developers.google.com/maps/terms, under: 

>10. License Restrictions
>
>10.1 Administrative Restrictions.
>
>a) No access to APIs or Content except through the Service. You will not access the Maps API(s) or the Content except through the Service. For example, you must not access map tiles or imagery through interfaces or channels (including undocumented Google interfaces) other than the Maps API(s).

ol3-google-maps **does** use the service provided by Google to request their tiles.

That being said, because of that, the library also comes with limitations.  See: https://github.com/mapgears/ol3-google-maps/blob/master/LIMITATIONS.md

Other tiles providers, such as Bing, HERE, Mapbox, etc. do not have this kind of constraint, i.e. it is legal to use OpenLayers natively to request the tiles, therefore it's much easier and smoother to include those.  If you absolutely need Google Maps and your project is simple enough to use their API only, then it is recommended to use their API only.  If you absolutely need OpenLayers, then ol3-google-maps is a nice alternative.

Also, please read the "Our commitment" of the readme: https://github.com/mapgears/ol3-google-maps#our-commitment

HTH,

Alexandre D.

**Comment by adube** [comment]
One other useful piece of info: Google themselves approuved a student for their Google Summer of Code last year to work on enhancements for ol3-google-maps.  That's an other "plus" right there.

**Comment by LSG8** [comment]
Thank you for the information
