### ISSUE TITLE
Hiding map when zoom in/out

### ISSUE THREAD

**Issue by szlicar** [mapgears/ol3-google-maps#196]
Hi,

I've changed my current GIS web app with the olgm script and works great, except a small issue with different zooming functionality comparing to default behavior when using OL3 or Google Maps independent. It seems like that when zoom change event is triggered, the layer gets hidden before starting loading tiles in the new zoom level. The result is that map display gets hidden (showing only background of map holder) before it starts loading the tiles for new zoom level. 

The default behavior on OL3 and Google Maps used independent is animating the map to new zoom and loading the tiles for new zoom when the animated old tiles are still shown, so there's no empty screen between zooming.

I'd just like to know if you think that the issue could be solved and if you can give me some additional tips how to implement that. I have some knowledge of OL3, but not so much on Google Maps Javascript API.

Thanks, S

**Comment by adube** [comment]
Here's how OLGM implements OpenLayers and Google Maps together.  An Google Maps map, using their official API, is created.  Then, an OpenLayers map is put on top of it, as a control that takes 100% of the size of the google maps element container.

Then, all navigation tools / interactions from Google Maps are disabled.  Therefore, when we pan the map, we pan the OpenLayers's map. OLGM listens to changes that occur to the OL map and gives them to the Google Maps one.  Panning isn't an issue, as setting the center of a map works smoothly between the two.

The main issues come with zooming in/out.  Prior to OpenLayers 3.20.0, only one event was fired while zooming in, with the resolution being the one "at the end of the animation".  So, when we told Google Maps "hey, zoom to that level", let's say from level 0 to 3, it did its one animation that keeps the tiles while animating.

Now, with OpenLayers >= 3.20.0, the event is fired *while* animating.  In other words, instead of only once, we ask Google Maps to change its zoom level multiple times... and even in fraction while the animation is in progress (i.e. 0, 0.2, 0.4, 0.6, etc...).  Google Maps doesn't like that.  It's not supposed to be supported to set a "fractionnal zoom" in Google Maps, but it kinda half-work...  Anyway (getting off track), that causes the tiles to disapear while animating.  That's for google maps.

Then, there's the overlaid images, i.e. a WMS layer added to OpenLayers gets added directly to Google Maps as an overlay.  While changing zoom levels, it doesn't stay visible.  That's probabely something that could be enhanced with more work in OLGM.  PRs are welcomed, btw.

That's pretty much it.  I hope it helps.

References:

 * https://github.com/mapgears/ol3-google-maps/issues/153
 * https://github.com/mapgears/ol3-google-maps/issues/160
 * https://stackoverflow.com/questions/41166831/google-maps-fractional-zoom-only-works-3-times

**Comment by adube** [comment]
You might also be interesed in this example: http://mapgears.github.io/ol3-google-maps/examples/dist/examples/watchoptions.html

When "watching", OLGM will pick the layer in question, turn it invisible in OL and create it in Google Maps.  That ensures a fluid animation (especially for vector features).  For WMS, it doesn't do much good.  I.e. while the "watch image layers" is OFF, the layer is kept in OL (not drawn in Google Maps), so when zooming in, the animation is the one of OpenLayers, which isn't that bad.

Maybe that could help you...

**Comment by josecrespoc** [comment]
Hi adube,

Do you know how I can load the layer Street View road availability?

I think the URL will be similar than this: http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}

Many thanks

**Comment by adube** [comment]
> Hi adube,
> 
> Do you know how I can load the layer Street View road availability?
> 
> I think the URL will be similar than this: [http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}](http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D)
> 
> Many thanks

Hello @josecrespoc 

Your question seems unrelated to the topic of this issue.  It also seems to be a "pure Google Maps" question, so I suggest that you try asking on Stack Overflow.

Happy coding!

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
