### ISSUE TITLE
added layers are not coordinated with google map

### ISSUE THREAD

**Issue by guyBy** [mapgears/ol3-google-maps#216]
did something change with google api.
search and +/- in addition to selected layer do not correspond with google map, and an offset is generated during zoom/move operations.
Thanks

**Comment by adube** [comment]
Something did change Google Maps as part of 3.32, which may affect how things are handled in olgm.  See the [Google Maps API Release Notes](https://developers.google.com/maps/documentation/javascript/releases).  There seems to be a new renderer.

I can see that there's a difference in behaviour between 3.31 and 3.32.  See the live olgm example here:http://mapgears.github.io/ol3-google-maps/examples/dist/examples/latest.html. The animation is now kinda slow, but at least it's smooth.  With 3.31, it was fast but kinda looked broken.

Other than the animations being slow, I don't see the other problems you describe.  Would you please elaborate, or provide a live demo?

**Comment by mstenta** [comment]
I think I know what's causing this - I ran into a similar issue a while back (and again now that I'm refactoring our map code). Originally reported in the farmOS issue queue in 2015 here: https://www.drupal.org/project/farm_area/issues/2546306

Summary of the issue:

> the Google Maps API does not allow you to zoom past a certain level. This makes sense, they only have imagery for certain zoom levels. Unfortunately, if you ask the API for tiles at a higher zoom level, it doesn't return empty tiles as you might expect - instead it returns the same map tiles as before (at the max zoom level). So the Google Maps tiles make it LOOK like you're only zoomed into 20, but everything else in Openlayers is actually zoomed to 24 (for example).

To put it another way: OpenLayers lets you keep zooming in, but the Google layer stops zooming when it reaches it's own maximum. So if you are drawing shapes using the Google base layer as reference, your drawing is not actually where you think it is.

In my old code, I hacked a workaround into place which would automatically switch to the ROADMAP layer if it detected that the Google layer wasn't able to zoom any farther.  I did that with the following:

```js
+    var mapTypeId = gmap.getMapTypeId();
     data.map.getView().on('change:resolution', function() {
       gmap.setZoom(data.map.getView().getZoom());
+
+      // If gmap won't zoom in any farther, switch to ROADMAP.
+      if (gmap.getZoom() < data.map.getView().getZoom()) {
+        gmap.setMapTypeId(google.maps.MapTypeId.ROADMAP);
+      } else {
+        gmap.setMapTypeId(mapTypeId);
+      }
     });
```

I'm not sure if there's a better solution.

**Comment by mstenta** [comment]
Here is a screen recording of the issue. It was a challenge to make a GIF less than 10mb (Github limit) so it's very short. But it shows zooming in on a vector feature over the Google Hybrid layer. Watch how the Google layer stops zooming but the vector layer keeps zooming.

![GIFrecord_2020-01-06_110535](https://user-images.githubusercontent.com/95381/71830437-bb018500-3074-11ea-8166-99861414309f.gif)

So if you can imagine, drawing new features on the Google layer after it has stopped zooming results in incorrect shapes/alignments.

**Comment by mstenta** [comment]
I'm not sure if I'll be able to use the same workaround I used in my old code with the new ol3-google-maps library. Seems like it would need to be in the ol3-google-maps library itself in order to have access to `gmap` object.

Is this something that would be worth providing as a pull request? Or is it too much of a hack?

**Comment by mstenta** [comment]
I also found this: https://developers.google.com/maps/documentation/javascript/maxzoom

Google Maps has an API to get the max zoom level at a given lat/lon (because it varies based on location). I wonder if we could use that and limit the max zoom of the layer accordingly. Seems complicated...

**Comment by mstenta** [comment]
I hope I didn't hijack this issue. Reading the original description now I'm wondering if it's not the same. Sorry @guyBy - does this sound like the issue you were reporting?

**Comment by adube** [comment]
@mstenta I had a similar issue in the past, but I was only dealing with OpenLayers.  I had 2 base layers (only one of them could be active at a time), and both had different maximum zoom levels and I wanted to provide a way to prevent zoomin it onto a level that didn't exist, and also when switching from one baselayer to an other I wanted to zoom out automatically, if needed.

I wanted to let OpenLayers take care of managing those restrictions, which is done on the level of the `ol.View` object.  When a view is created, you can set min/max zoom/resolution restrictions, but you can't update them afterwards, so I ended up creating one view for each baselayer and when switching to this layer I set the according view at the same time, limiting the proper zoom levels.

What I'm describing as solution I did fits what I required, and what you describe also fits your requirements, but I'm not sure if one or the other could fit as a feature to implement in OLGM.

I think it would make more sense to have something implemented in ol-ext, i.e.: http://viglino.github.io/ol-ext/

For example, if I implemented my solution, it would be some sort of 'interaction' that listens layers that are added in the map and that we could identify as base maps, and implement the logic of switching the map's view in there.

It could make sense to start a thread with the ol-ext community about this, to see if it could be worth creating something... otherwise, I think this could be considered something that has to be handled manually by the developer playing Legos with all these Libraries using plain JS.

Thoughts?

**Comment by mstenta** [comment]
Thanks for sharing that @adube - very helpful! I agree it seems that this is just something that needs to be solved on a per-project basis for now. If it can be made more general in `ol-ext` that would be great too! Thank you for sharing that - first time I've seen it!

I am right now working to refactor my previous hack to work with `ol3-google-maps`, so I'll share the code snippet here when I get it working, for anyone who might find it useful.

**Comment by mstenta** [comment]
See below for the workaround I'm using. See comments in code for explanation.

Limitations:

- It changes the `MapTypeId` to `roadmap` when it's zoomed beyond Google's limit. This still has the same problem, but compared to `satellite` it makes a big if you are trying to draw features. So this isn't the perfect solution, but it helps. If there is a better way, please share!

Variables that were defined before this code:

- `map`:  the OL map
- `googleLayers`: an array of Google layers that were added to the map

```js
  // Activate Google Maps.
  const olGM = new OLGoogleMaps({ map });
  const gmap = olGM.getGoogleMapsMap();
  olGM.activate();

  // Google Maps has a limitation in the way it handles maximum zoom levels.
  // If the OpenLayers map is zoomed beyond the maximum zoom level supported by
  // the Google layer (which varies by location), the OL map will zoom, but the
  // Google map will not. This can cause issues if you are viewing/drawing
  // vector shapes and using the Google layer as a guide, because it will not
  // stay in sync with the OpenLayers zoom level.
  //
  // To get around this, we listen for changes in the map resolution, and if we
  // find that the Google Maps zoom level is less than the OpenLayers zoom level
  // (indicating that it wasn't able to zoom farther), then change the map type
  // to the roadmap, which may still be incorrect but at least it is less
  // distracting than satellite/terrain.
  //
  // For reference:
  //   - https://www.drupal.org/project/farm_map/issues/2680273
  //   - https://github.com/mapgears/ol3-google-maps/issues/216#issuecomment-571177483
  let mapTypeId;
  googleLayers.forEach((layer) => {
    layer.on('change:visible', (e) => {
      if (e.target.getVisible() && e.target.get('mapTypeId')) {
        mapTypeId = e.target.get('mapTypeId');
      }
    });
  });
  this.map.getView().on('change:resolution', () => {
    const zoom = this.map.getView().getZoom();
    gmap.setZoom(zoom);
    if (gmap.getZoom() < zoom) {
      gmap.setMapTypeId('roadmap');
    } else {
      gmap.setMapTypeId(mapTypeId);
    }
  });
```

**Comment by FrankyBoy** [comment]
In my tests this does not seem to be related to max zoom at all, I can reproduce this on any zoom level. The "trick" seems to be to zoom before the animation finishes, but I am still experimenting.

**Comment by luciman** [comment]
@FrankyBoy I think you're talking about something else. Looking at your example from #301 I think you mean the synchronization of the zoom between layers. Just put the watch tile option on true. :)

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
