### ISSUE TITLE
Rotation feature glitches

### ISSUE THREAD

**Issue by tzarick** [mapgears/ol3-google-maps#221]
When trying to add functionality for rotating the map (using the rotation example (https://github.com/mapgears/ol3-google-maps/blob/master/examples/rotation.js) as a guide, the map seems to be confused about the axis. Dragging down causes the map to move sideways, and zooming out or in zooms incorrectly off-axis because it seems like there is a hidden rotated layer underneath or something. This behavior happens in the rotation example as well (which also freezes after rotating once). 

The angle set by the `rotation` field of the view seems to be correlated with the amount of off-axis confusion there is when attempting to drag the map around. The map also doesn't actually rotate but seems to respond to mouse dragging in the way that it would if it were rotated.

Is there a way around this?

**Comment by adube** [comment]
I remember this feature used to work properly in the past.  I saw the current behaviour and I wasn't like that before.  This could be due to a change in Google Maps API and/or OpenLayers.

This will have to be fixed, as there's currently no way around this other than that.

A contribution would be welcomed.  Please, feel free to work on a patch for this and I'd be happy to review.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
