### ISSUE TITLE
Google map does not start zoom animations until after OL animations are complete

### ISSUE THREAD

**Issue by justinstenning** [mapgears/ol3-google-maps#234]
I have found that when performing zoom operations the google layer does not update until after the OL animation has completed.

For example, the following will exaggerate the issue by setting OL zoomDuration to 5secs:
```interactions: defaults({zoomDuration: 5000}),```

To remove the delay altogether:
```interactions: defaults({zoomDuration: 0}),```

If toggling the google layer you would need to reset this somehow.

It seems unrelated to the new Google rendering engine, as issue remains for v3.31.

**Comment by adube** [comment]
You are right about this issue.  Thanks for reporting it.

However, it may be related to the new Google rendering engine.  v3.31, which used the old one, has been deprecated and is no longer returned, see: https://maps.googleapis.com/maps/api/js?v=3.31

Also: https://developers.google.com/maps/documentation/javascript/versions

> The version number is specified with v=n.nn. 
> You can choose v=3.34, v=3.33, or v=3.32. 
> Version numbers are updated once per quarter (see Quarterly updates).

I remember that back with v3.31 and less the issue was not present, but it may be a combinaison of other things as well...

Would you please provide a patch to fix this issue?  A contribution would be welcome.

**Comment by justinstenning** [comment]
I'm experiencing a few other graphical glitches that I am not seeing in the examples, so will wait until I have had a chance to look into these also (they result in overlays not animating in line with the google map, appearing to slide in from the top left/bottom right corner when zooming).

**Comment by spazzarama** [comment]
Setting zoomDuration: 0, causes other unwanted side effects - specifically for single tile ImageWMS layer. When zooming in/out, the layer will slide in from the top left or bottom right. Using zoomDuration: 0, doesn't have the problem. I couldn't reproduce with the WMS example in ol3-google-maps, but perhaps it is a timing issue and the layer I have access to is a lot quicker.

**Comment by spazzarama** [comment]
It appears to be a broader issue with ImageWMS sources. If I change the WMS example to point to a local Geoserver installation, the same behaviour occurs with the ImageWMS source of the states. I'll submit another issue.

**Comment by justinstenning** [comment]
The glitches I was experiencing were from #228. The zoom issue itself remains.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
