### ISSUE TITLE
Capture and export tile to image

### ISSUE THREAD

**Issue by kimchirichie** [mapgears/ol3-google-maps#239]
Map exporting using `canvas.toBlob(function)` like in [openlayers export example](https://openlayers.org/en/latest/examples/export-map.html) does not work as expected.
All other layers, such as vector layer, can be seen in the generated image file. However, the google maps tile is excluded in the generated image. Viz,
![download](https://user-images.githubusercontent.com/9277484/50249302-784e0b80-0392-11e9-9b2f-4b2234e1e3da.png)
Figure 1. the generated png image is transparent where google map tiles should have been shown.

I've tried using html2canvas, but the library does not support CSS rotation, and thus not a good replacement candidate.

**Comment by adube** [comment]
Exporting a Google Maps map would be a violation of their Terms of Service.  You simply can't do that.

https://cloud.google.com/maps-platform/terms/

> 3.2.4 Restrictions Against Misusing the Services.
> 
> Customer will not extract, export, scrape, or cache Google Maps Content for use outside the Services.

But, for the record, it is not exported in OLGM because it uses their Google Maps JS API to render the Google Maps map as required by their Terms of Service, and OpenLayers is rendered on top of it.  So, exporting OL only will only output layers from OL, excluding GM.

I'm closing this issue because there can't be a fix for it.

Thank you very much for your interest in OLGM.
