### ISSUE TITLE
Config to allow watch options for individual Vector layers

### ISSUE THREAD

**Issue by justinstenning** [mapgears/ol3-google-maps#247]
I have multiple vector layers. One of these I wish to change the styles of at runtime to reflect different edit modes. The styles are quite complex and are not currently supported by OLGM (e.g. geometry function to display points for the vertices of a polygon as seen in this OL example: https://openlayers.org/en/latest/examples/polygon-styles.html).

I am able to either set all vector layers to be unmanaged by OLGM (#68 and #111), or because I need to specify an array of styles, force an exception in getStyleOf(...) that prevents the addition of this layer to OLGM when it is added to the map. I would prefer to be able to specify watch options for each individual layer.

The real underlying issue is that changing the styles at runtime is not supported, and that arrays of styles and the more deep features of OL styles are not supported. My thoughts are that switching to unmanaged at the times I need these particular features is a more practical solution then trying to go further with styles support.

@adube Do you have any thoughts on this before I look at implementing?

**Comment by adube** [comment]
Hello @spazzarama!

Implementing a way to avoid a particular layer from being watched by an herald seems like a good idea.  Here's how it would see this.  Such layers could have a specific property set that would tell heralds not to watch them.

The `LayersHerald` would be responsible of doing that check, in the `watchLayer_` and `unwatchLayer_` methods.  The property could be something like `olgmWatch` that would need to be set to `false` in order to be ignored.  For example (subset of the watchoptions examples)

```
const vector = new VectorLayer({
  olgmWatch: false,
  source: source
});
```

Then, it's a matter of checking if `layer.get('olgmWatch') !== false`.

What do you think?

**Comment by justinstenning** [comment]
Sounds good, not sure if it would be able to respond to changes to the setting, I will look at that secondary to just being able to do it when layer added.
