### ISSUE TITLE
zoomFactor on OL map view is not honoured by google maps

### ISSUE THREAD

**Issue by jllodra** [mapgears/ol3-google-maps#295]
A zoomFactor for the ol map view different from 2 (or 4, 6, 8...)  is not honoured by google maps.

Is this a known issue or am I missing something?

E.g. If I set a zoomFactor of 1.5,
the google layer only zooms in every second time I click on the "+" button.

**Comment by adube** [comment]
This looks like a bug, because if I recall correctly OLGM is supposed to support fractionnal zoom levels and different zoom levels (I may be wrong).

If there's a bug in OLGM about this, then it would make sense to create an example that showcases the issue and with a fix would show that it's supported.

The "View herald" is responsible of synchronizing the OL view with the GM maps: https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/herald/View.js, in "setZoomAndCenter".  That's the place to start investigating.

A patch would be welcome.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
