### ISSUE TITLE
Does it support openlayer 6 cdn version?

### ISSUE THREAD

**Issue by EAGLEliuS** [mapgears/ol3-google-maps#325]
As title

**Comment by adube** [comment]
Officially, no. The code of OLGM depends on code provided by OpenLayers and if I recall correctly they both need to be compiled together.

It's been a while since I last used the library and I only used it as a ES Module so I may be wrong.  Originally, there was no intention of making the library work with the cdn version of OL.

Cheers

**Comment by EAGLEliuS** [comment]
Does OLGM have a CDN version that supports ol 6?

**Comment by adube** [comment]
OLGM does not provide a self-contained build, no.

You may be interested in reading #278.  Maybe that could help.
