### ISSUE TITLE
Error Styling Features

### ISSUE THREAD

**Issue by kluger888** [mapgears/ol3-google-maps#332]
I got an ERROR TypeError: style.getStroke is not a function on styling features on Vector Layer.
The reason is that in OpenLayers you are able to set style arrays (features.setStyle([style1, style2])) .
If you do so the exception occurs in the gm.js file method createStyleInternal(style, mapIconOptions, opt_index);

This method expects an style but no array.

For me it is important to use arrays on features cause of complex styling functionality.

**Comment by adube** [comment]
Hello @kluger888.  Thanks for reporting the issue.

If you could work on a fix for this, it would be much appreciated.  Thanks.

**Comment by sherryaten** [comment]
Hi,
The issue occurs because the style variable is getting an array of styles or object. I managed to fix it by changing the code in olgm/gm.js

let stroke;
  if(style instanceof Array){
    stroke = style[0].getStroke();
  }else{
    stroke = style.getStroke();
  }

The same rules apply to getFill() and getImage().

Then I managed to update it on olgm/herald/Feature.js to getZIndex() and getImage()

Regards

**Comment by adube** [comment]
Thanks.

You can provide a Pull Request if you want to contribute this fix to the project.

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352
