### ISSUE TITLE
Ol3-Google-Maps v0.4 vector layer problems

### ISSUE THREAD

**Issue by luciman** [mapgears/ol3-google-maps#60]
With Ol3-Google-Maps v0.4 the vector layer is not visible with OSM, also in your examples (concept, vector etc.).

**Comment by adube** [comment]
A patch would be welcome.  Thanks for reporting this.

**Comment by samuellapointe** [comment]
If I understand correctly, when OL3-Google-Maps is activated, the OpenLayers vector objects are made invisible and are drawn using the google maps API on the google maps layer. Activating the OSM layer while OL3-Google-Maps is active means that the OSM layer is hiding the features rendered by google maps.

In short, there's no point in activating OL3-Google-Maps if the google maps layer isn't visible. Should this be fixed in the library itself? We could re-enable vector objects when the google maps layer isn't visible anymore.

**Comment by adube** [comment]
OL3-Google-Maps can stay active, i.e. it can do its "magic", but it should only does so while a Google layer is visible.

**Comment by adube** [comment]
#78 fixed this issue.
