### ISSUE TITLE
use google layer and use ol.layer.Vector 

### ISSUE THREAD

**Issue by Ian-Ya** [mapgears/ol3-google-maps#69]
In my project, I use a data to create point just like 
http://openlayers.org/en/v3.7.0/examples/earthquake-clusters.html
when the layer is OSM or Mapquest ,which is OK.
but when I use the google layer, in create first point,
my function cannot get the feature,
so I cannot use size to create point and the text on it 
Is anyone can help me
Sorry about my terror English

**Comment by adube** [comment]
Clusters are not currently supported by OL3-Google-Maps.  See: #52.

**Comment by Ian-Ya** [comment]
But after chrome error massage, my map will show the Clusters on the google layer,
so I have any way to let error massage not show??
I have try "try{ my Cluster function }catch(err){}","if(!feature)return"" " ,but it will show another error massage or not show any point or google`s point

**Comment by Ian-Ya** [comment]
I have changed Process today and I found the error It occurred in OLGoogleMaps({ map: Map }).activate();this function. In my project, I have changed the interactions and  I use Map to save new ol.Map. So hope those massage can help you understand what is my problem.
Thx.

**Comment by adube** [comment]
Clusters are not currently supported and we don't expect it to work at all for now with the default behavior of OLGM, that is: make the layers render in Google Maps instead of OpenLayers.

As an alternative, you could disable this behavior, that is: make OpenLayers render the layers, not Google Maps.  This means that clusters would work, but the synchronization between OL3 and Google Maps wouldn't match perfectly, i.e. you'll see this when zooming.  To enable this, try:

```
var olGM = new olgm.OLGoogleMaps({
  map: map, // map is the ol.Map instance,
  watchVector: false // <-- this tells OLGM to 'not watch' vector layers, i.e. let them be created in OL3 normally
});
```

There's an issue about showing that exact feature: #68.

**Comment by Ian-Ya** [comment]
The consequent is I want now.
Thank you so much.

**Comment by adube** [comment]
Excellent.  I'll close this issue, then.  Thanks for your interest in OLGM.
