### ISSUE TITLE
OLGM Version: v0.4 google map doesn't load automatic when first loading

### ISSUE THREAD

**Issue by yungfei1989** [mapgears/ol3-google-maps#74]
Hi I have using your olgm.js v0.4, why google map doen't load automatically like the previous v.02 which I use. althought I have use your suggetion to add :+1: 

`window.setTimeout(function () {
                var olGM = new olgm.OLGoogleMaps({map: map}); // map is the ol.Map instance
                olGM.activate();
            }, 1000);`

How can I get olgm.js without compiled to .min.js?

Thanks

**Comment by adube** [comment]
Hello.
- I don't recall v0.2 automatically loading Google Maps.  I'm not sure why you imply, otherwise
- The source code containing the minimized code is `olgm.js` and the one that's not is `olgm-debug.js`, see:
  - https://github.com/mapgears/ol3-google-maps/releases/tag/v0.4, more specifically the .zip file:
  - https://github.com/mapgears/ol3-google-maps/releases/download/v0.4/ol3-google-maps-v0.4.zip

**Comment by yungfei1989** [comment]
hmmm...the case is when first load with switcher and google map as default map, it will show blank map until we do click in map, it will show google map, in previous version it will automatically render google map when first load map

**Comment by adube** [comment]
Would you please share a demo, maybe on JSFiddle ?
